version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lavanda-plex-backend-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7lno1r3muddd"
s3_prefix = "lavanda-plex-backend-serverless"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
